// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  about: [
    'index',
    'features',
    'bibliography',
    'glossary',
  ],
  ontology: [
    {
      type: 'category',
      label: 'Classes',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Ontology',
        description: ' ',
        slug: '/ontology',
        keywords: [],
      },
      items: [
        'Event',
        'Group',
        'Person',
        'Place',
        'Organization',
        'Thing',
      ],
    },
  ],
  download: [
    'download',
  ],
  sdk: [
    {
      type: 'category',
      label: 'Languages',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Software Development Kits (SDKs)',
        description: ' ',
        slug: '/sdk',
        keywords: [],
      },
      items: [
        {type: 'autogenerated', dirName: 'sdk'},
      ],
    },
  ],
};

export default sidebars;
