// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  overview: [
    'index',
    'features',
    'glossary',
  ],
  classes: [
    'Person',
    'Thing',
  ],
  sdk: [
    {
      type: 'category',
      label: 'Languages',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Software Development Kits (SDKs)',
        description: ' ',
        slug: '/sdk',
        keywords: [],
      },
      items: [
        {type: 'autogenerated', dirName: 'sdk'},
      ],
    },
  ],
};

export default sidebars;
